version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src/Config/LogiSync.db:/app/Config/LogiSync.db
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_FRONTEND_URL=${REACT_APP_FRONTEND_URL}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - VITE_APP_BACKEND_API_URL=${VITE_APP_BACKEND_API_URL}
      - VITE_APP_GOOGLE_APIKEY=${VITE_APP_GOOGLE_APIKEY}