services:
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REACT_APP_FRONTEND_URL_PROD=${REACT_APP_FRONTEND_URL_PROD}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
    volumes:
      - ./backend/src/Config:/app/src/Config
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_APP_BACKEND_API_URL_PROD=${VITE_APP_BACKEND_API_URL_PROD}
      - VITE_APP_EXCHANGE_API_KEY=${VITE_APP_EXCHANGE_API_KEY}
      - VITE_APP_NEWS_API_KEY=${VITE_APP_NEWS_API_KEY}
      - VITE_APP_GOOGLE_APIKEY=${VITE_APP_GOOGLE_APIKEY}
    depends_on:
      - backend
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  backend_data: