services:
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REACT_APP_FRONTEND_URL=${REACT_APP_FRONTEND_URL}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - "3000:80"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - VITE_APP_BACKEND_API_URL=${VITE_APP_BACKEND_API_URL}
      - VITE_APP_GOOGLE_APIKEY=${VITE_APP_GOOGLE_APIKEY}

