# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - logisync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://logisync.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1d66eaf4d45d4aa9a36071c39391ae6f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d1db78d85ff54e0abcb979187155bccf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: logisync.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d66eaf4d45d4aa9a36071c39391ae6f }}/logisync-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'logisync'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_68e76e0de5834c53b84bf024155abd00 }}
        images: 'logisync.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d66eaf4d45d4aa9a36071c39391ae6f }}/logisync-frontend:${{ github.sha }}'