name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          registry: logisync.azurecr.io

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: logisync.azurecr.io/logisync-frontend:v1

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: logisync.azurecr.io/logisync-backend:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az aks get-credentials --resource-group LogiSync --name kubernete-logisync

      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v3
        with:
          manifests: |
            ./k8s/frontend-deployment.yaml
            ./k8s/backend-deployment.yaml
          images: |
            logisync.azurecr.io/logisync-frontend:v1
            logisync.azurecr.io/logisync-backend:v1
