name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-frontend:v1

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-backend:v1

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az webapp config container set --name logisync-frontend --resource-group LogiSync --docker-custom-image-name ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-frontend:v1 --docker-registry-server-url https://ghcr.io --docker-registry-server-user ${{ secrets.GHCR_USERNAME }} --docker-registry-server-password ${{ secrets.GHCR_TOKEN }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az webapp config container set --name logisync-backend --resource-group LogiSync --docker-custom-image-name ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-backend:v1 --docker-registry-server-url https://ghcr.io --docker-registry-server-user ${{ secrets.GHCR_USERNAME }} --docker-registry-server-password ${{ secrets.GHCR_TOKEN }}
