name: Build and Deploy to Azure App Service Homologation environment

on:
  push:
    branches:
      - homologation

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
          install: false
          use: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Build and push frontend homologation Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-homologation-frontend:v1
          build-args: |
            VITE_APP_BACKEND_API_URL=${{ secrets.VITE_APP_BACKEND_API_URL }}
            VITE_APP_GOOGLE_APIKEY=${{ secrets.VITE_APP_GOOGLE_APIKEY }}
        env:
          VITE_APP_BACKEND_API_URL: ${{ secrets.VITE_APP_BACKEND_API_URL }}
          VITE_APP_GOOGLE_APIKEY: ${{ secrets.VITE_APP_GOOGLE_APIKEY }}

      - name: Build and push backend homologation Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-homologation-backend:v1
        env:
          REACT_APP_FRONTEND_URL: ${{ secrets.REACT_APP_FRONTEND_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az webapp config appsettings set --name logisync-homologation-frontend --resource-group LogiSync --settings VITE_APP_BACKEND_API_URL=${{ secrets.VITE_APP_BACKEND_API_URL }} VITE_APP_GOOGLE_APIKEY=${{ secrets.VITE_APP_GOOGLE_APIKEY }}
            az webapp config container set --name logisync-homologation-frontend --resource-group LogiSync --container-image-name ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-homologation-frontend:v1 --container-registry-url https://ghcr.io --container-registry-user ${{ secrets.GHCR_USERNAME }} --container-registry-password ${{ secrets.GHCR_TOKEN }}

      - name: Restart Azure App Service for Frontend
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart --name logisync-homologation-frontend --resource-group LogiSync

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az webapp config appsettings set --name logisync-homologation-backend --resource-group LogiSync --settings REACT_APP_FRONTEND_URL=${{ secrets.REACT_APP_FRONTEND_URL }} SECRET_KEY=${{ secrets.SECRET_KEY }} REFRESH_SECRET_KEY=${{ secrets.REFRESH_SECRET_KEY }} EMAIL_USER=${{ secrets.EMAIL_USER }} EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            az webapp config container set --name logisync-homologation-backend --resource-group LogiSync --container-image-name ghcr.io/${{ secrets.GHCR_USERNAME }}/logisync-homologation-backend:v1 --container-registry-url https://ghcr.io --container-registry-user ${{ secrets.GHCR_USERNAME }} --container-registry-password ${{ secrets.GHCR_TOKEN }}

      - name: Restart Azure App Service for Backend
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart --name logisync-homologation-backend --resource-group LogiSync
